CREATE TABLE media.playlists (
    playlist_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK (char_length(btrim(name)) BETWEEN 1 AND 60),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX playlists_name_ci_unique
    ON media.playlists (lower(btrim(name)));

CREATE TABLE media.playlist_tracks (
    playlist_id BIGINT NOT NULL REFERENCES media.playlists(playlist_id) ON DELETE CASCADE,
    music_key BIGINT NOT NULL REFERENCES media.tracks(music_key) ON DELETE CASCADE,
    position INTEGER NOT NULL CHECK (position >= 0),
    PRIMARY KEY (playlist_id, music_key),
    UNIQUE (playlist_id, position)
);

CREATE INDEX playlist_tracks_music_key_idx
    ON media.playlist_tracks (music_key);
