/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/playback/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPlaybackSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/playback/tracks/{assetId}/key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["issueTrackKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminTracks"];
        put?: never;
        post: operations["uploadTrack"];
        delete: operations["deleteTracks"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/tracks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchTrack"];
        trace?: never;
    };
    "/v1/admin/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminPlaylists"];
        put?: never;
        post: operations["createPlaylist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/playlists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deletePlaylist"];
        options?: never;
        head?: never;
        patch: operations["renamePlaylist"];
        trace?: never;
    };
    "/v1/admin/playlists/{id}/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["replacePlaylistTracks"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{sha256}.ppm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEncryptedAsset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreatePlaybackSession: {
            fingerprintSha256: string;
            fingerprintVersion: number;
            devicePublicKey: {
                /** @constant */
                kty: "RSA";
                /** @constant */
                alg: "RSA-OAEP-256";
                n: string;
                e: string;
            };
        };
        PublicTrack: {
            /** Format: int64 */
            musicKey: number;
            /** Format: uuid */
            assetId: string;
            title: string;
            artist: string;
            audioFormat: components["schemas"]["AudioFormat"];
            coverUrl?: string | null;
            lyricUrl?: string | null;
            /** Format: int64 */
            plaintextSize: number;
            chunkSize: number;
            chunkCount: number;
            cipherUrl: string;
        };
        PublicPlaylist: {
            /** Format: int64 */
            playlistId: number;
            name: string;
            trackIds: number[];
        };
        PublicCatalog: {
            tracks: components["schemas"]["PublicTrack"][];
            playlists: components["schemas"]["PublicPlaylist"][];
        };
        PublicCatalogResponse: {
            data: components["schemas"]["PublicCatalog"];
        };
        PlaybackSession: {
            /** Format: date-time */
            expiresAt: string;
        };
        PlaybackSessionResponse: {
            data: components["schemas"]["PlaybackSession"];
        };
        IssuedKey: {
            /** Format: uuid */
            assetId: string;
            wrappedKey: string;
            /** @constant */
            algorithm: "RSA-OAEP-256";
            /** Format: date-time */
            expiresAt: string;
            /** Format: int64 */
            plaintextSize: number;
            chunkSize: number;
            chunkCount: number;
            noncePrefix: string;
            cipherSha256: string;
            audioFormat: components["schemas"]["AudioFormat"];
        };
        IssuedKeyResponse: {
            data: components["schemas"]["IssuedKey"];
        };
        AdminTrack: {
            /** Format: int64 */
            musicKey: number;
            /** Format: uuid */
            assetId: string;
            title: string;
            artist: string;
            audioFormat: components["schemas"]["AudioFormat"];
            coverPath?: string | null;
            lyricPath?: string | null;
            sortOrder: number;
            enabled: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        AudioFormat: "mp3" | "flac";
        AdminTrackList: {
            data: components["schemas"]["AdminTrack"][];
        };
        AdminTrackResponse: {
            data: components["schemas"]["AdminTrack"];
        };
        AdminPlaylist: {
            /** Format: int64 */
            playlistId: number;
            name: string;
            trackIds: number[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AdminPlaylistList: {
            data: components["schemas"]["AdminPlaylist"][];
        };
        AdminPlaylistResponse: {
            data: components["schemas"]["AdminPlaylist"];
        };
        PlaylistNameRequest: {
            name: string;
        };
        ReplacePlaylistTracksRequest: {
            trackIds: number[];
        };
        DeletePlaylistResult: {
            deleted: boolean;
        };
        DeletePlaylistResponse: {
            data: components["schemas"]["DeletePlaylistResult"];
        };
        TrackPatch: {
            title?: string;
            artist?: string;
            sortOrder?: number;
            enabled?: boolean;
        };
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail: string;
        };
    };
    responses: {
        /** @description Rate limit exceeded */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPublicCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enabled tracks and non-empty playlists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicCatalogResponse"];
                };
            };
        };
    };
    createPlaybackSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlaybackSession"];
            };
        };
        responses: {
            /** @description Session created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaybackSessionResponse"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    issueTrackKey: {
        parameters: {
            query?: never;
            header: {
                "X-Media-Fingerprint": string;
            };
            path: {
                assetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wrapped content key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedKeyResponse"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    listAdminTracks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All tracks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTrackList"];
                };
            };
        };
    };
    uploadTrack: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    archive: string;
                    title: string;
                    artist: string;
                    sortOrder?: number;
                    enabled?: boolean;
                };
            };
        };
        responses: {
            /** @description Track published */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTrackResponse"];
                };
            };
            /** @description Archive too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    deleteTracks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    ids: number[];
                };
            };
        };
        responses: {
            /** @description Tracks deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patchTrack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackPatch"];
            };
        };
        responses: {
            /** @description Track updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTrackResponse"];
                };
            };
        };
    };
    listAdminPlaylists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All playlists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPlaylistList"];
                };
            };
        };
    };
    createPlaylist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaylistNameRequest"];
            };
        };
        responses: {
            /** @description Playlist created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPlaylistResponse"];
                };
            };
            /** @description Playlist name already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deletePlaylist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Playlist deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletePlaylistResponse"];
                };
            };
            /** @description Playlist not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    renamePlaylist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaylistNameRequest"];
            };
        };
        responses: {
            /** @description Playlist renamed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPlaylistResponse"];
                };
            };
            /** @description Playlist not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    replacePlaylistTracks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplacePlaylistTracksRequest"];
            };
        };
        responses: {
            /** @description Playlist membership replaced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPlaylistResponse"];
                };
            };
            /** @description Playlist not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown track id */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getEncryptedAsset: {
        parameters: {
            query?: never;
            header?: {
                Range?: string;
            };
            path: {
                sha256: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full PPM1 object */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description PPM1 byte range */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
